version: '3'
services:
  db:
    image: mysql:5.6.17
    container_name: mysql-db-save-user
    ports:
      - '3306:3306'
    restart: always
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=saveuser
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./docker/volume_mysql:/var/lib/mysql
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_saveuser
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./docker/rabbitmq:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456